# Generated by Django 5.0.2 on 2024-03-08 19:49

import embed_video.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Movie", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tvseries",
            name="trailer_url",
            field=embed_video.fields.EmbedVideoField(default="", null=True),
        ),
    ]
