# Generated by Django 5.0.2 on 2024-03-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Movie", "0002_alter_tvseries_trailer_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tvseries",
            name="trailer_url",
            field=models.URLField(default="", null=True),
        ),
    ]
