# Generated by Django 5.0.3 on 2024-04-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0006_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='is_like_playlist',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
